[package]
name = "totall"
version = "0.1.1"
authors = ["robiot"]
description = "totall - Count lines in all files in directories and subdirectories easily"
license = "MIT"
repository = "https://github.com/robiot/totall"
edition = "2018"

[dependencies]
linecount = "0.1.0"
path-clean = "0.1.0"